### ISSUE TITLE
image

### ISSUE THREAD

**Issue by yocki-s** [veritrans/SNAP-Woocommerce#1]
image resource for Wiki
![snap-woo1](https://cloud.githubusercontent.com/assets/6572247/18000579/f769912a-6ba8-11e6-903b-058791f11501.png)
![snap-woo2](https://cloud.githubusercontent.com/assets/6572247/18046616/e5a30fd2-6e02-11e6-8d95-d14f4cc3f001.png)
![snap-woo3](https://cloud.githubusercontent.com/assets/6572247/18047236/02f0fda8-6e06-11e6-9031-4efc1372f86b.png)
![snap-woo4](https://cloud.githubusercontent.com/assets/6572247/18081946/d4cb9cb4-6ec6-11e6-81bf-df8f8e8c0b44.png)
![snap-woo5](https://cloud.githubusercontent.com/assets/6572247/18082399/f3ba7558-6ec8-11e6-805a-e671837f2895.png)

**Comment by rizdaprasetya** [comment]
<img width="627" alt="Screen Shot 2020-06-16 at 11 26 08" src="https://user-images.githubusercontent.com/13027142/84732132-14c38f00-afc5-11ea-8318-18e9709aa964.png">
<img width="559" alt="Screen Shot 2020-06-16 at 11 27 12" src="https://user-images.githubusercontent.com/13027142/84732141-19884300-afc5-11ea-871d-559b914b4a13.png">
