### ISSUE TITLE
Konsumen sudah bayar, tapi status order tetap "pending payment"

### ISSUE THREAD

**Issue by agoyspace** [veritrans/SNAP-Woocommerce#26]
Selamat malam, saya sudah coba pasang plugin midtrans di woocommerce dan puji Tuhan sukses bisa melakukan transaksi di environment sandbox. Namun ada satu yang janggal, ntah hanya saya saja atau emang sistemnya kayak gini. 

Jadi, saya coba test sebagai konsumen untuk membeli barang di web saya dan pakai metode pembayaran midtrans tentunya. Udah tuh pilih metode pembayaran transfer atm pake BCA, dan saya pake testing credential nya midtrans (BCA VA). Pembayaran oke, sudah dianggap sistem midtrans kalau dia sudah lunas membayar. Namunnnn, status order di woocommerce tetep aja 'Pending Payment" dan tidak ada notifikasi order masuk sama sekali untuk admin/ penjualnya di email. Masa iya si penjual dikit dikit harus ngecek woocommerce nya?

Jadi itu yang saya tanyakan, kenapa konsumen udah bayar lunas, tapi status order tidak berubah (tetap Pending Payment aja)?

Terima kasih,
Agoy

![image](https://user-images.githubusercontent.com/24309279/54868466-49936700-4dbf-11e9-86b8-64954b6930e6.png)
![image](https://user-images.githubusercontent.com/24309279/54868572-801db180-4dc0-11e9-88d9-cc44e17d1380.png)
![image](https://user-images.githubusercontent.com/24309279/54868576-8b70dd00-4dc0-11e9-8b3d-45cf1c0bc49c.png)
![image](https://user-images.githubusercontent.com/24309279/54868558-52386d00-4dc0-11e9-83d2-ec4723bb1b63.png)

**Comment by rizdaprasetya** [comment]
Hi @agoyspace 

Silahkan pastikan sudah mengikuti:
https://github.com/veritrans/SNAP-Woocommerce#midtrans-map-configuration
Tanpa itu, status transaksi tidak akan bisa berubah otomatis.

Untuk pertanyaan terkait Midtrans, sebaiknya ditanyakan ke email support[at]midtrans.com untuk response yg lebih cepat & channel yg tepat.

Thanks.

**Comment by reizhafajrian** [comment]
ini gimana solusinya?saya mendevelop aplikasi di android callbacknya selalu pending

**Comment by adityarizqi** [comment]
> ini gimana solusinya?saya mendevelop aplikasi di android callbacknya selalu pending

iya ane jg untuk payment sih berhasil, tp setiap requst pasti pending, kalo cmn manfaatin handler sulit juga ntar klo user bayar sebelom klik konfirmasi

**Comment by reizhafajrian** [comment]
sepertinya untuk di mobile ketika klik button selesaikan pembayaran bawaan midtrans tidak minta request status terbaru,makanya status selalu pending

**Comment by rizdaprasetya** [comment]
Hi @reizhafajrian @adityarizqi pertanyaan tersebut berbeda dari pertanyaan awal yg ada di thread Github Issue ini, jadi akan berbeda penyelesaian.

Yang kalian maksudkan berarti untuk transaksi di Android menggunakan Mobile SDK Android Midtrans ya? Android SDK merupakan frontend, sedangkan untuk tipe pembayaran Bank Transfer (atau metode asynchronous sejenis) [terjadi secara asynchronous](https://mobile-docs.midtrans.com/#transaction-status), dimana pembayaran akan diupdate realtime di sisi backend. Jadi sisi frontend belum mendapat update status pembayaran secara realtime.

Sebaiknya setelah mendapat frontend callback pending, silahkan lakukan [get-status API call](https://docs.midtrans.com/en/after-payment/get-status), untuk mendapat status transaksi yang paling update.

Untuk kedepannya hal ini akan  dijadikan masukan untuk tim SDK Midtrans sebagai improvement di versi-versi selanjutnya.

Semoga membantu. Thanks.
