### ISSUE TITLE
Email new order tidak masuk ke email Customer

### ISSUE THREAD

**Issue by ivansuharyadi** [veritrans/SNAP-Woocommerce#27]
Halo

1. Order di felancy.co.id
2. Order sudah masuk dengan status PendingPayment
3. Email new order tidak terkirim ke email customer(menggunakan payment method lain terkirim)

Terimakasih

**Comment by rizdaprasetya** [comment]
Hi @ivansuharyadi untuk jawaban yg lebih cepat silahkan untuk pertanyaan seputar produk midtrans bisa email ke support[at]midtrans.com

- Pastikan integrasi sudah diselesaikan dengan benar, terutama step: https://github.com/veritrans/SNAP-Woocommerce#midtrans-map-configuration kalau belum diselesaikan dengan benar, payment status tidak akan terupdate di sisi woocommerce anda.
- Pastikan pada payment popup customer sudah memilih payment method dan confirm

Customer akan mendapat email dari woocommerce seperti berikut, pastikan configurasi woocommerce anda diset untuk kirim email ke customer (default):
https://web.archive.org/web/20190402043417/http://mailnesia.com/mailbox/raizertest/453971917

**Comment by ivansuharyadi** [comment]
Hi @rizdaprasetya terimakasih penjelasannya :)
