### ISSUE TITLE
enhanced ecommmerce & masalah kartu kredit

### ISSUE THREAD

**Issue by mclsto** [veritrans/SNAP-Woocommerce#28]
Hi, @rizdaprasetya 

Saya menggunakan plugin midtrans woocommerce untuk salah satu website saya. 

## Pertama

Semua opsi pembayaran sudah bisa, hanya saja untuk beberapa metode pembayaran dibawah ini tidak ter-redirect ke halaman "**Order Received**" nya woocommerce.

Saya tahu kita bisa setting finish URLnya (https://domainsaya.com/checkout/order-received/) tetapi sistem woocommerce mengalihkan user ke halaman "Order received" dengan beberapa parameter.

domainsaya.com/checkout/order-received/[**no order id**]/?key=wc_order_ [**kodeunik**]

Nah bagaimana caranya untuk menambahkan parameter itu karena **no order id** dan wc_order_**[kodeunik]** dibuat oleh sistem secara otomatis.

Berikut daftar pembayaran yang tidak langsung ke halaman "Order received"
* BCA KlikPay
* CIMB Clicks
* Danamon Online Banking
* e-Pay BRI
* Line Pay e-cash / Mandiri e-cash

Mengapa hal di atas menjadi penting?

Karena bila kita ingin menerapkan fitur **enhanced ecommerce** Google Analytics di woocommerce, perlu halaman "Order received" dengan beberapa parameter di URLnya.

## Kedua
Saya mencoba menggunakan fitur ke 2,3, dan 4 dari midtrans woocommerce ini.

* **Midtrans Credit Card Direct**

Ketika klik tombol pembayaran, ada pesan **Error! Metode pembayaran tidak aktif**

Bagaimana cara mengaktifkannya? Apakah ada video tutorialnya?

* **Midtrans Online Installment**
* **Midtrans Offline Installment**

Untuk kedua metode di atas, muncul error

> Midtrans Exception: Midtrans Error (400): {"error_messages":["installment.installment_terms does not support installment term"]} | Request url: https://app.sandbox.midtrans.com/snap/v1/transactions. 
Plugin Title: Midtrans Online Installment

Saya sudah atur minimal pembayarannya tapi tetap seperti di atas masalahnya.

Bagaimana cara memperbaikinya? Apakah ada video tutorialnya?

Terima kasih

**Comment by rizdaprasetya** [comment]
Hi @mclsto 
1# sayangnya untuk jenis pembayaran yg involve redirect ke payment provider / bank, finish url redirectnya mengikuti spesifikasi dari payment provider / bank tersebut, dan tidak bisa ditambah parameter tertentu karena limitasi dari mereka.

2# Issue tersebut bisa disebabkan karena akun Sandbox anda tidak aktif untuk credit card & installment. Silahkan share Merchant ID anda untuk kami reactivate.

Untuk response terkait pertanyaan integrasi yg lebih cepat silahkan email support[at]midtrans.com
Thanks

**Comment by pusatkursus** [comment]
Bagaimana cara mengaktifkan akun Sandbox untuk credit card & installment?

**Comment by pusatkursus** [comment]
berikut id saya G833162342
