### ISSUE TITLE
Redirection status code 301, 302 and 303 are not supported. Use 307 or 308 instead.

### ISSUE THREAD

**Issue by Wie-CBD** [veritrans/SNAP-Woocommerce#31]
Salam, 

Saya sedang mencoba integrasi Snap-Woocommerce dengan menggunakan plugin Midtrans - WooCommerce Payment Gateway, dan saya sudah mengikuti semua langkah disini : https://github.com/veritrans/SNAP-Woocommerce#midtrans-map-configuration

Proses checkout berjalan dengan mulus (dalam konfigurasi sandbox), Namun saya selalu mendapatkan error : `Redirection status code 301, 302 and 303 are not supported. Use 307 or 308 instead.` Status di Woocommerce juga macet di 'pending payment'.

Apakah ada setting lain yang harus saya lakukan untuk integrasi midtrans?

Terima kasih.

**Comment by rizdaprasetya** [comment]
Halo @Wie-CBD URL silahkan info URL yg diisi di dashboard? Ini karena salah URL, atau servernya ada redirect. URL harus diisi dengan url yg benar
`http://[URL ke wordpressnya]/?wc-api=WC_Gateway_Mid` coba jg ganti `http://` jadi `https://`

thanks

**Comment by Wie-CBD** [comment]
@rizdaprasetya Terimakasih, ternyata saya kurang teliti - link nya sudah benar, tapi belum ganti `http://` jadi `https://`
