### ISSUE TITLE
Notification error

### ISSUE THREAD

**Issue by zzumm** [veritrans/SNAP-Woocommerce#4]
Entah benar atau tidak menanyai disini, krn via email support tdk di respon :(

Sementara masih sandbox

Terkendala dgn issue notification endpoint, ketika test di MAP hasilnya;

**Failed**
Response status is '404' not '200' atau Response status is '500' not '200'

Semua settingan sudah sesuai dokumentasi termasuk url yg lain dgn menggunakan url

http://sub.domain.saya/?wc-api=WC_Gateway_Midtrans

dicoba pointing ke domain lain, malah bisa :(

any idea?? Thanks!

**Comment by rizdaprasetya** [comment]
Email support untuk weekend akan direspon dalam 4-6 jam.
Apakah masih mengalami kendala yang sama? Silahkan dijabarkan lebih lanjut via email ke support@midtrans.com karena kami perlu mengetahui MID akun Midtrans Anda & alamat webnya.

Thanks

**Comment by zzumm** [comment]
Terima kasih sudah merespon.

Ya, sampai tadi juga masih mengalami kendala tersebut, dengan respon:
Failed
Response status is '500' not '200'
Yang saya test callback pada MAP.
Utk domain selama sandbox di http://berani.co, serta MID adalah M100592
Dari semua yg saya lakukan sudah mengikuti apa yg tertera di
https://github.com/veritrans/SNAP-Woocommerce
Bahkan kesemuanya juga sudah diperbaharui utk versi terbaru (php, wp, wc,
dan plugins midtrans)
Any idea?

Thank you

2017-01-23 9:43 GMT+07:00 Rizda Dwi Prasetya <notifications@github.com>:

**Comment by rizdaprasetya** [comment]
Apakah sudah kirim email ke support@midtrans.com ? Silahkan infokan subject email atau alamat email yg anda gunakan untuk mengirim, agar bisa saya cek. Karena informasi yang anda berikan di atas tidak bisa digunakan untuk pengecekan apapun karena tidak lengkap.

Thanks
