### ISSUE TITLE
Easier to understand payment option name on `Midtrans Credit Card Direct` to prevent merchant misusing it

### ISSUE THREAD

**Issue by rizdaprasetya** [veritrans/SNAP-Woocommerce#43]
Some merchant is confused, and think that `Midtrans Credit Card Direct` payment options is the only way they can accept card payment. Although the main payment options has already include card payment.

Need to change the name to be more explanatory.

https://github.com/veritrans/SNAP-Woocommerce/blob/5c38e7de9d8477d981b8101816dfb91e172f412e/class/class.midtrans-gateway-paymentrequest.php#L120-L129

- Change `Midtrans Credit Card Direct` 
to 
`Midtrans Optional Card in-Browser Payment UI`

- Change `Credit Card Payment via Midtrans` 
to 
`Alternative Card Payment form using in-browser payment UI (leave it disabled if not sure)`

Include this changes on next feature release. Lower priority.

**Comment by aalexanderkevin** [comment]
done on https://github.com/veritrans/SNAP-Woocommerce/pull/42/commits/c6a74ae0891e87b9fdef4634c3c2eab499e1c825
