### ISSUE TITLE
Allow merchant to specify Acquring Bank on credit card full payment (main payment) option

### ISSUE THREAD

**Issue by ariefruf** [veritrans/SNAP-Woocommerce#44]
Hi, Is there anyway i can do this in the online payment method?

As far i can see the option only available in the in browser credit card payment. And i have to use the online method because i use bank transfer etc payment methods too.

there probably should be easier way to change this option in the setting for your consideration later on for non developer.

Or at least put in the tutorial which plugin file i have to edit

**Comment by rizdaprasetya** [comment]
Hi @ariefruf 
Can you explain further why do you need to specify `acquiring bank` on the main-payment?
Currently main-payment is using auto-optimized acquiring bank that you have in your account. To ensure acquiring is distributed accordingly. If you specify 1 acquiring bank, all payment will only go through that 1, which means all the other acquiring bank is unused. On Production Midtrans Account, it is better to explicitly ask to disable any unused acquiring bank, to avoid being deactivated from bank side and may cause issue. In most case, you will only have 1 acquiring bank on Production account, so no need to specify `acquiring bank` on the main-payment, from Woocommerce side.

If you really need manual modification, after this line of code:
https://github.com/veritrans/SNAP-Woocommerce/blob/aae0f7decbc48fa1ba313c2190b3c7330eab0a5d/class/class.midtrans-gateway.php#L95

You can add:
```
$params['credit_card']['bank'] = 'mandiri';
```
replace `mandiri` with any preferred valid acquiring bank name.

**Comment by ariefruf** [comment]
Okay, thanks for the answer

I need to know how to change the acquiring bank because in our company have new contract with a bank that explicitly said that we have to use them as acquiring bank. And I don't know you can deactivate the other acquiring when i asked this question, and still don't know how. From midtrans side i presume?

But i still think its better to have option in this case. If its a months back before we have finalized the contract i would say i want to switch acquiring without deactivating the other acquiring as a backup because 
1. i need to abide by the contract clausul while the higher ups negotiate.
2. If i deactivate the other acquiring and the negotiation broke it would do damage to our payment 
    system

I believe that is kind of case is rare, but it did happened because there is a lot of miscommunication in that personal experience

**Comment by rizdaprasetya** [comment]
Ah got it, thanks for the detailed explanation that help us understand the use-case scenario @ariefruf 
in terms of use-case about contract, backup, and migration, yes your use-case is valid.
We'll try to add this feature on future updates. We'll keep this issue open until it got implemented.

Current possible workaround: 
- you can refer to manual modification on the code, suggested above. Or

> From midtrans side i presume?

- Yes from Midtrans side, you can contact the Merchant's Midtrans representative (account manager, or support[at]midtrans.com) and ask which bank to disable/enable.

**Comment by rizdaprasetya** [comment]
Hi @ariefruf 
This feature has been added to the latest release of `Midtrans WooCommerce v2.18.4`. Acquiring bank field is added to the main payment option config page. You can try to update. Will close this issue now. Let us know if issue persist.

Thanks!
