### ISSUE TITLE
Pending payment status

### ISSUE THREAD

**Issue by jankrix** [veritrans/SNAP-Woocommerce#50]
Halo, saya memiliki masalah dimana order yang saya test via woocommerce (sandbox), status di midtrans sudah oke sudah masuk tapi di woocommerce tetep pending sehingga saya harus approve manual.

**Comment by jankrix** [comment]
ternyata ada salah interpretasi manual yang di website midtrans dengan yang ada di github, yang di github guidenya lebih jelas. Untuk ini saya tutup issuenya. Terima Kasih

**Comment by rizdaprasetya** [comment]
Terim kasih informasinya, 
Silahkan diinfokan detailnya jika ada informasi yang kurang jelas. Untuk jawaban yang lebih responsif silahkan kontak melalui email support@midtrans.com jika mengalami issue.
thanks
