### ISSUE TITLE
Biaya transaksi dibebankan ke customer

### ISSUE THREAD

**Issue by mtaupiq** [veritrans/SNAP-Woocommerce#53]
Hallo dev, saya mau bertanya kalo misalkan saya mau menambahkan biaya transaksi ke customer apakah benar modifikasi nya di file ini.

https://github.com/veritrans/SNAP-Woocommerce/blob/9bd6102d6b7401bc16f72e3b42bec5daca38b9dd/abstract/abstract.midtrans-gateway.php#L256

**Comment by mtaupiq** [comment]
> $items[] = array(       
                                  'id' =&gt; 'biayatransaksi',        
                                  'price' =&gt; 4000,       
                                  'quantity' =&gt; 1,        
                                  'name' =&gt; 'Biaya Transaksi'      
                      );

**Comment by rizdaprasetya** [comment]
Halo, ya betul bisa ditambahkan seperti itu, item/fee tambahan tersebut
akan menambah total di halaman pembayaran. Atau alternatif lain tanpa
mengubah langsung code plugin midtrans, melalui function woocommercenya
sendiri:
https://awhitepixel.com/blog/woocommerce-checkout-add-custom-fees/
Semoga membantu. Terima kasih.

**Comment by mtaupiq** [comment]
Sip 👍 Terimakasih
