### ISSUE TITLE
503

### ISSUE THREAD

**Issue by tjemberoot** [veritrans/SNAP-Woocommerce#67]
instalasi berhasil , namun klik setting langsung keluar error 503 pakai Version 2.32.0

**Comment by rizdaprasetya** [comment]
Hi @tjemberoot , thanks for reaching out.
Boleh didetailkan lebih lanjut 503nya seperti apa:
- silahkan cek & apakah ada error message dari PHP/WP error log?
- apakah ada contoh screenshot?
Silahkan provide info di atas untuk mempermudah pengecekan.

Ada juga kemungkinan issue karena environment server WP anda di Host tidak memenuhi requirement, atau ada conflict dengan plugin 3rd party lainnya. Anda juga bisa coba:
- disable semua plugin lain, baru enable plugin Midtrans. Atau 
- coba install dulu di WP+Woocommerce yg fresh baru terinstall, untuk memastikan issuenya bukan di plugin Midtrans.

Terima kasih.

**Comment by tjemberoot** [comment]
maaf problem di hostingnya , memory langsung naik begitu ada midtrans plugin
