### ISSUE TITLE
Undefined variable: order_id in class.midtrans-gateway.php

### ISSUE THREAD

**Issue by agung-wete** [veritrans/SNAP-Woocommerce#7]
PHP Notice:  [Undefined variable: order_id in /var/www/vhosts/xxx/httpdocs/wp-content/plugins/midtrans-woocommerce/class/class.midtrans-gateway.php on line 536](https://github.com/veritrans/SNAP-Woocommerce/blob/746c3ba1020039a54ec69ef6c00c92a24ba8a2a2/class/class.midtrans-gateway.php#L529-L536)

**Comment by rizdaprasetya** [comment]
Duplicate issue entry. see #6

**Comment by agung-wete** [comment]
Ini tidak hanya terjadi waktu testing, tapi juga saat midtrans kirim hasil transaksi
