### ISSUE TITLE
Logo Mandiri VA / Bill

### ISSUE THREAD

**Issue by arkgnan** [veritrans/SNAP-Woocommerce#78]
untuk metode pembayaran mandiri bill belum ada logo nya. jika mengacu pada folder images [disini](https://github.com/veritrans/SNAP-Woocommerce/tree/master/public/images/payment-methods) sepertinya perlu ditambahkan

padahal untuk bank transfer setidaknya harus ada 4 logo untuk bri va, bni va, permata va, mandiri bill
![image](https://user-images.githubusercontent.com/17277219/221833020-c9c76ada-1940-4ab3-b916-32b784f6ae8c.png)

**Comment by rizdaprasetya** [comment]
Hi @arkgnan untuk Mandiri Bill Payment sebetulnnya sudah ada. Nama filenya saja yg agak berbeda, namanya adalah `echannel`:
- https://github.com/veritrans/SNAP-Woocommerce/blob/master/public/images/payment-methods/echannel.png
Jadi silakan gunakan file tersebut ya.

Contohnya sudah dipakai secara default untuk sub-payment button seperti berikut:
https://github.com/veritrans/SNAP-Woocommerce/blob/ea83a7492de0390e5b5698147d3359683509c6d5/class/sub-specific-buttons/class.midtrans-gateway-sub-echannel.php#L12-L13

Thanks.

**Comment by arkgnan** [comment]
thanks
