### ISSUE TITLE
Salah Nomor rek virtual

### ISSUE THREAD

**Issue by fahreza007** [veritrans/SNAP-Woocommerce#8]
Saya setial kali transaksi pake akun virtual yg di berikan oleh woocomers(midtrans) tapi tidak pernah sukses selalu nomor rekening tidak ada padahal sudah saya sama kan.
dan pengaturan juga sudah saya sesuaikan seperti langkah'' yg ada. dan juga kalau lewat kartu kredit memang bisa. Tolong solusinya

**Comment by rizdaprasetya** [comment]
Silahkan diinfokan lebih jelas: 

- Apa environment payment yg digunakan? Production atau Sandbox?
- Ada contoh order ID atau nomor rekeningnya?
- Mencoba membayar di mana? Untuk environment sandbox, bayar menggunakan simulator berikut:
https://snap-docs.midtrans.com/#bank-transfer

Jika butuh bantuan lebih detail, bisa juga melalui email support@midtrans.com

> Issue tagged as `invalid` because not a specific issue to the Snap-Woocommerce plugin, but Midtrans in general

**Comment by fahreza007** [comment]
Iya makasih pak itu sudah bisa. Terus saya coba pindah ke production tapi tidak ada akun bank yg bisa di pilih untuk transaksi itu kenapa ya?
Saya sudah mengikuti langkah'' yg ada di dokumentasi.

Saya pakai woocomerce pak

**Comment by rizdaprasetya** [comment]
@fahreza007 
Silahkan ikuti langkah berikut
https://support.midtrans.com/hc/id/articles/115011159927-Apakah-ada-dokumen-legal-yang-perlu-saya-kirimkan-
Thanks.

**Comment by fahreza007** [comment]
ok makasih pak. Terus berkarya.=
