### ISSUE TITLE
Tidak ada metode pembayaran yang tersedia. Mungkin error ini disebabkan oleh pihak kami. Silakan hubungi kami jika Anda membutuhkan bantuan untuk melakukan pemesanan.

### ISSUE THREAD

**Issue by silmarweny** [veritrans/SNAP-Woocommerce#81]
Tidak ada metode pembayaran yang tersedia. Mungkin error ini disebabkan oleh pihak kami. Silakan hubungi kami jika Anda membutuhkan bantuan untuk melakukan pemesanan.

![2024-01-25_115913](https://github.com/veritrans/SNAP-Woocommerce/assets/157534895/dbf8c9b3-c67b-42b4-8aaf-29318fabca21)
![2024-01-25_120005](https://github.com/veritrans/SNAP-Woocommerce/assets/157534895/c5286ca2-fae8-484a-9bf0-37f243970611)

mohon bantuan gan

**Comment by godfreu** [comment]
Apa sudah ada solusi untuk masalah ini? Saya juga mengalaminya.

**Comment by silmarweny** [comment]
Masalah Terselesaikan dengan edit halaman **Checkout** menjadi _Shortcode_

`[woocommerce_checkout]`

![111](https://github.com/veritrans/SNAP-Woocommerce/assets/157534895/a89e50c7-7a93-4c42-9649-cd5f756f9cfb)
